Repository AY2324S1-CS2103T-T09-2/tp, pull requests merged in 2023-11, with the labels that each got.

#137 Add lock, unlock, change password commands
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ChangePasswordCommand.java
  src/main/java/seedu/address/logic/commands/LockCommand.java
  src/main/java/seedu/address/logic/commands/UnlockCommand.java
  src/main/java/seedu/address/logic/commands/imports/ImportClientCommand.java
  src/main/java/seedu/address/logic/commands/imports/ImportDeveloperCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ChangePasswordCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnlockCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/Password.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/java/seedu/address/ui/DeveloperCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/DeveloperListCard.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/ProjectListCard.fxml
Labels: priority-medium

#139 Show tab changes and what previous instruction for undo redo
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/add/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/add/AddDeveloperCommand.java
  src/main/java/seedu/address/logic/commands/add/AddProjectCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteDeveloperCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditDeveloperCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditProjectCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
Labels: type.task

#155 Find deadline command
  src/main/java/seedu/address/logic/commands/find/FindDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/list/ListProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/find/FindDeadlineCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/ui/ProjectCard.java
Labels: type.story, priority-high

#157 Fixing problems in add and delete roles
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/deleteRoles/DeleteClientRoleCommand.java
  src/main/java/seedu/address/logic/commands/deleteRoles/DeleteDeveloperRoleCommand.java
  src/main/java/seedu/address/model/client/ClientRoles.java
  src/main/java/seedu/address/model/developer/DeveloperRoles.java
Labels: type.task

#161 Update UG
  docs/UserGuide.md
Labels: priority-high

#164 Update find and parameters in UG
  docs/UserGuide.md
Labels: documentation

#220 Test cases update
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditDeveloperDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeveloperTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/DeveloperUtil.java
  src/test/java/seedu/address/testutil/EditDeveloperDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: test cases

#227 Fix bugs in find by project
  docs/UserGuide.md
  docs/UserGuide2101.md
  docs/team/waseemingly.md
  pword.txt
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/find/FindClientCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindDeveloperCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindProjectCommandParser.java
  src/main/java/seedu/address/model/client/AddressClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/DocumentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/EmailClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/NameClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/OrganisationContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/PhoneClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/ProjectClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/RoleClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/AddressDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/EmailDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/GithubIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/NameDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/PhoneDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/ProjectDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/RoleDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/project/DeadlineContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/project/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicate.java
Labels: bug, Documentation-Bug

#229 Update PPP
  docs/team/mingyu-wan.md
Labels: documentation

#246 Ug n dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddDeveloperRoleSequenceDiagram.puml
  docs/diagrams/DeleteDeveloperRoleSequenceDiagram.puml
  docs/diagrams/ListDeveloperCommand.puml
  docs/diagrams/UndoRedoActivityDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/isRemovableRole.puml
  docs/images/AddDeveloperRoleSequenceDiagram.png
  docs/images/DeleteDeveloperRoleSequenceDiagram.png
  docs/images/ListDeveloperSequenceDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/images/isRemovableRole.png
  src/main/java/seedu/address/model/client/ClientRoles.java
  src/main/java/seedu/address/model/developer/DeveloperRoles.java
Labels: documentation

#247 Add use cases and planned enhancements
  docs/DeveloperGuide.md
  gradle/wrapper/gradle-wrapper.jar
Labels: documentation

#250 Add test cases
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/addroles/AddClientRoleCommand.java
  src/main/java/seedu/address/logic/commands/addroles/AddDeveloperRoleCommand.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/addroles/AddClientRoleCommandTest.java
  src/test/java/seedu/address/logic/commands/addroles/AddDeveloperRoleCommandTest.java
  src/test/java/seedu/address/logic/commands/deleteroles/DeleteClientRoleCommandTest.java
  src/test/java/seedu/address/logic/commands/deleteroles/DeleteDeveloperRoleCommandTest.java
  src/test/java/seedu/address/logic/commands/list/ListProjectCommandTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
Labels: test cases

#251 modify UG
  docs/UserGuide.md
  docs/images/UG UI 1.png
  docs/images/UG UI 2.png
  docs/team/mingyu-wan.md
Labels: documentation

#296 Update user guide format
  docs/UserGuide.md
  pword.txt
Labels: documentation
