Repository AY2324S1-CS2103T-T09-2/tp, pull requests merged in 2023-10, with the labels that each got.

#36 Modification of Developer Guide
  docs/DeveloperGuide.md
Labels: type.story

#43 Modifications to developer guide
  docs/DeveloperGuide.md
Labels: type.task

#45 Update AboutUs.md
  docs/AboutUs.md
  docs/images/ncmathan.png
  docs/team/ncmathan.md
Labels: documentation

#54 Add parameters, update AddCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DateJoined.java
  src/main/java/seedu/address/model/person/Password.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/model/person/Username.java
  src/main/java/seedu/address/model/tag/Project.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, type.story, priority-high

#55 Modify access rights
  src/main/java/seedu/address/logic/CurrentUser.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority-high, type.task

#59 Modify edit command to account for access rights
  src/main/java/seedu/address/logic/DummyCurrentUser.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditOthersCommand.java
  src/main/java/seedu/address/logic/commands/EditSelfCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority-high, type.task

#68 Add import command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Labels: type.story, priority-high

#133 Add find by multiple attributes
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/find/FindClientCommand.java
  src/main/java/seedu/address/logic/commands/find/FindDeveloperCommand.java
  src/main/java/seedu/address/logic/commands/find/FindProjectCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/find/FindClientCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindDeveloperCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindProjectCommandParser.java
  src/main/java/seedu/address/model/client/AddressClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/EmailClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/NameClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/PhoneClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/ProjectClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/RoleClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/AddressDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/CombinedDeveloperPredicate.java
  src/main/java/seedu/address/model/developer/EmailDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/NameDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/PhoneDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/ProjectDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/developer/RoleDeveloperContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/KeywordPredicateFactory.java
  src/main/java/seedu/address/model/person/ProjectContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindDeveloperCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority-high

#136 Implement undo redo function
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDeveloperCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/TabIndex.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/add/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/add/AddDeveloperCommand.java
  src/main/java/seedu/address/logic/commands/add/AddProjectCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditDeveloperCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditProjectCommand.java
  src/main/java/seedu/address/logic/commands/find/FindClientCommand.java
  src/main/java/seedu/address/logic/commands/find/FindDeveloperCommand.java
  src/main/java/seedu/address/logic/commands/find/FindProjectCommand.java
  src/main/java/seedu/address/logic/commands/list/ListClientCommand.java
  src/main/java/seedu/address/logic/commands/list/ListDeveloperCommand.java
  src/main/java/seedu/address/logic/commands/list/ListProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/find/FindClientCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindDeveloperCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindProjectCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListClientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.task
